---
title: "Rent Analysis"
output:
  html_document:
    toc: true
    df_print: paged
  html_notebook:
    toc: true
    fig_width: 3
    fig_height: 3
    fig_caption: true
  pdf_document:
    toc: true
  word_document:
    toc: true
editor_options:
  chunk_output_type: inline
---
```{r setup, include=FALSE}
dir.create("figuresBN", showWarnings = FALSE)  
knitr::opts_chunk$set(fig.path = "figuresBN/")
```
--------------------------------------------------------------------------------
# Main code from here
```{r}
library(LinRegInteractive)
data(munichrent03)
data <- munichrent03
```
# Load the dataset
```{r}
str(data)
names(data)
```

```{r}
summary(data)
```

rentsqm = rent * area
```{r}
round(data$rent[2]/data$area[2],2)
data$rentsqm[2]
round(data$rent[100]/data$area[100],2)
data$rentsqm[100]
```

```{r}
# (1) Bỏ biến rent
data$rentsqm <- NULL
```

```{r}
head(sort(table(data$district), decreasing = TRUE), 7)
head(sort(table(data$district[data$location %in% c("top", "good")]), 
          decreasing = TRUE),7)
```

```{r}
head(sort(table(data$district[data$location %in% c("top", "good")]), 
          decreasing = TRUE),7)
```

```{r}
library(dplyr)
cols <- c("bathextra", "bathtile", "cheating", "upkitchen", "wwater")
total_n <- nrow(data)
feature_yes_count <- sapply(cols, function(col) {
  sum(data[[col]] == "yes", na.rm = TRUE)
}) |> unname()
feature_summary <- data.frame(
  Feature = cols,
  Count = as.integer(feature_yes_count),
  Percent = round(100 * feature_yes_count / total_n, 1)
)
print(feature_summary)
```

```{r}
head(sort(table(data$district[data$bathextra == "yes" &
    data$cheating == "yes" &  data$upkitchen == "yes" &
    data$wwater == "yes" &data$bathtile=="yes"
    ]), decreasing = TRUE), 7)
```

```{r}
library(DataExplorer)
plot_histogram(data)
```

```{r}
shapiro.test(data$rent)
shapiro.test(data$area)
```

```{r}
table(data$room)
table(data$yearc)
```

```{r}
names(data[-c(1,2,3,4,8,9)])
```
 
```{r echo=TRUE, warning=FALSE}
library(gRbase)
library(Rgraphviz)
library(bnlearn)
library(gRain)
library(ggm)
library(igraph)
```

```{r}
data$rooms <- as.factor(data$rooms)
data$location <- as.factor(as.character(data$location))
```

```{r}
data$yearc <- round(data$yearc)
data$year_group <- cut(data$yearc,
  breaks = c(1917, 1959, 1969, 1989, 2001),
  labels = c("1918-1959", "1960-1969", "1970-1989", "1990-2001"),right = TRUE)
length(data$year_group) == nrow(data)
```

```{r}
district_counts <- sort(table(data$district), decreasing = TRUE)
district_counts
district_ordered <- names(district_counts)
```

```{r}
area1_index <- c(1, 2, 3, 4, 5, 6, 9 ,11, 12, 16, 21)
district_ordered[area1_index]
```

```{r}
area2_index <- c(7, 8, 10, 13, 14, 15, 17, 20, 22)
district_ordered[area2_index]
```

```{r}
area3_index <- setdiff(1:length(district_ordered), c(area1_index, area2_index))
district_ordered[area3_index]
```

```{r}
district_group_info <- data.frame(district = district_ordered,
                                  group = NA)
district_group_info$group[area1_index] <- "Area1"
district_group_info$group[area2_index] <- "Area2"
district_group_info$group[area3_index] <- "Area3"
data$district_group <- 
  district_group_info$group[match(data$district, district_group_info$district)]
data$district_group <- as.factor(data$district_group)
sum(table(data$district_group)) == nrow(data)
```

```{r}
data_bn <- data[, !(names(data) %in% c("yearc", "district"))]
data_bn$rent <- as.numeric(data_bn$rent)
data_bn$area <- as.numeric(data_bn$area)
```

```{r}
data_disc <- discretize(data_bn, method = "hartemink",breaks = 3,ibreaks = 60,
                        idisc = "quantile")
str(data_disc)
```

```{r}
# boot.strength(data = , R = 300, 
#               algorithm = c("pc.stable","hc","mmhc"),
#               algorithm.args = list())
```

```{r warning=FALSE}
set.seed(42)
boot_pc <- boot.strength(data = data_disc, R = 500, algorithm = "pc.stable",
                         algorithm.args = list(test = "mi"))
boot_hc <- boot.strength(data = data_disc, R = 500, algorithm = "hc", 
                         algorithm.args = list(score = "bic"))
boot_mmhc <- boot.strength(data = data_disc, R = 500, algorithm = "mmhc")
```

```{r}
avgnet_pc <- averaged.network(boot_pc[boot_pc$direction>=0.5,], 
                              threshold = 0.85)
avgnet_hc <- averaged.network(boot_hc[boot_hc$direction>=0.5,], 
                              threshold = 0.85)
avgnet_mmhc <- averaged.network(boot_mmhc[boot_mmhc$direction>=0.5,], 
                                threshold = 0.55)
```

```{r}
mean_strength <- function(strength, DAG) 
  {arcs_net <- arcs(DAG)
  matched_strength <- strength[
    apply(strength[, c("from", "to")], 1, function(x)
      any(apply(arcs_net, 1, function(y) all(x == y)))
    ),]
  mean(matched_strength$strength)
  }
results <- data.frame(
  Algorithm = c("pc.stable", "hc", "mmhc"),
  BIC = c(score(avgnet_pc,   data = data_disc, type = "bic"),
          score(avgnet_hc,   data = data_disc, type = "bic"),
          score(avgnet_mmhc, data = data_disc, type = "bic")),  
  Egdes=c(dim(arcs(avgnet_pc))[1],
          dim(arcs(avgnet_hc))[1],
          dim(arcs(avgnet_mmhc))[1]),
  Mean_Strength = c(mean_strength(boot_pc,   avgnet_pc),
                    mean_strength(boot_hc,   avgnet_hc),
                    mean_strength(boot_mmhc, avgnet_mmhc))
  )
results
```

```{r}
graphviz.plot(avgnet_pc, main = "Averaged Model - pc.stable")
graphviz.plot(avgnet_hc, main = "Averaged Model - hc")
graphviz.plot(avgnet_mmhc, main = "Averaged Model - mmhc")
```

```{r}
avgnet_pc <- averaged.network(boot_pc[boot_pc$direction>=0.5,], 
                              threshold = 0.75)
avgnet_hc <- averaged.network(boot_hc[boot_hc$direction>=0.5,], 
                              threshold = 0.75)
avgnet_mmhc <- averaged.network(boot_mmhc[boot_mmhc$direction>=0.5,], 
                                threshold = 0.75)
```

```{r}
graphviz.plot(avgnet_pc, main = "Averaged Model - pc.stable")
graphviz.plot(avgnet_hc, main = "Averaged Model - hc")
graphviz.plot(avgnet_mmhc, main = "Averaged Model - mmhc")
```

```{r}
results <- data.frame(
  Algorithm = c("pc.stable", "hc", "mmhc"),
  BIC = c(score(avgnet_pc,   data = data_disc, type = "bic"),
          score(avgnet_hc,   data = data_disc, type = "bic"),
          score(avgnet_mmhc, data = data_disc, type = "bic")),  
  Egdes=c(dim(arcs(avgnet_pc))[1],
          dim(arcs(avgnet_hc))[1],
          dim(arcs(avgnet_mmhc))[1]),
  Mean_Strength = c(mean_strength(boot_pc,   avgnet_pc),
                    mean_strength(boot_hc,   avgnet_hc),
                    mean_strength(boot_mmhc, avgnet_mmhc))
  )
results
```
hc (75%)
```{r}
final_mod_dag=averaged.network(boot_hc[boot_hc$direction>=0.5,],threshold = 0.75)
```

```{r echo=TRUE, message=TRUE, warning=TRUE}
fit = bn.fit(final_mod_dag, data = data_disc, method = "mle")
```

```{r}
has_na <- sapply(fit, function(node) any(is.na(unlist(node$prob))))
names(has_na)[has_na]
```

```{r}
gr_fit <- as.grain(fit)
```

```{r}
bnlearn::parents(fit,"rent")
bnlearn::children(fit,"rent")
```

```{r}
dsep(fit,"district_group","bathextra","rent")
data_disc[c(18),][c(2,4,7:8,11,1)]
```

```{r}
data_disc[c(114),][c(2,4,7:8,11,1)]
```

```{r}
dsep(fit,"rent","rooms","area")
```

```{r}
dsep(fit,"rent","location","year_group")
dsep(fit,"rent","district_group","year_group")
dsep(fit,"rent","cheating","year_group")
```

```{r}
dsep(fit,"area","year_group")
dsep(fit,"rooms","district_group")
dsep(fit,"area","cheating")
dsep(fit,"area","location")
dsep(fit,"area","year_group","rent")
dsep(fit,"rooms","district_group","rent")
dsep(fit,"area","cheating","rent")
dsep(fit,"area","location","rent")
```

```{r}
library(lattice)
districts <- levels(data_disc$district_group)
loc_levels <- c("good", "top")
distr <- do.call(rbind, lapply(districts, function(d) {
  prob <- querygrain(setEvidence(gr_fit, evidence = list(district_group = d)), nodes = "location")$location
  data.frame(District = d, Location = loc_levels, Prob = as.numeric(prob[loc_levels]))
}))
barchart(Location ~ Prob | District, data = distr,
         layout = c(3, 1), xlab = "probability",
         strip = strip.custom(factor.levels = paste("Pr(location |", districts, ")")),
         col = c("gray40", "gray80"),
         panel = function(...) {
           panel.barchart(...)
           panel.grid(h = 0, v = -1)
         })
```

```{r}
levels(data_disc$rent)
cpquery(fit,event = rent %in% c("[77.31,406.132]","(406.132,687.072]"),
        evidence = (district_group == "Area1"),
        n = 10^5)
cpquery(fit,event = rent %in% c("[77.31,406.132]","(406.132,687.072]"),
        evidence = (district_group == "Area2"),
        n = 10^5)
cpquery(fit,event = rent %in% c("[77.31,406.132]","(406.132,687.072]"),
        evidence = (district_group == "Area3"),
        n = 10^5)
```

```{r}
querygrain(setEvidence(gr_fit, nodes = "cheating", states = "yes"),nodes = c("wwater"),type = "joint")
```

```{r}
levels(data_disc$year_group)
querygrain(setEvidence(gr_fit, nodes = "year_group", states = "1918-1959"),
           nodes = c("cheating"),type = "joint")["yes"]

querygrain(setEvidence(gr_fit, nodes = "year_group", states = "1960-1969"),
           nodes = c("cheating"),type = "joint")["yes"]

querygrain(setEvidence(gr_fit, nodes = "year_group", states = "1990-2001"),
           nodes = c("cheating"),type = "joint")["yes"]
```

```{r}
levels(data_disc$rent)
querygrain(setEvidence(gr_fit, nodes = "year_group", states = "1918-1959"),
           nodes = c("cheating"),type = "joint")["yes"]

querygrain(setEvidence(gr_fit, nodes = "year_group", states = "1960-1969"),
           nodes = c("cheating"),type = "joint")["yes"]

querygrain(setEvidence(gr_fit, nodes = "year_group", states = "1990-2001"),
           nodes = c("cheating"),type = "joint")["yes"]
```

```{r}
querygrain(setEvidence(gr_fit, nodes = "rent", states = "[77.31,406.132]"),
           nodes = c("upkitchen", "bathextra"), type = "joint")["yes","yes"]

querygrain(setEvidence(gr_fit, nodes = "rent", states = "(406.132,687.072]"),
           nodes = c("upkitchen", "bathextra"), type = "joint")["yes","yes"]

querygrain(setEvidence(gr_fit, nodes = "rent", states = "(687.072,1789.55]"),
           nodes = c("upkitchen", "bathextra"), type = "joint")["yes","yes"]

querygrain(setEvidence(gr_fit, nodes = "rent", states = "(687.072,1789.55]"),
           nodes = c("upkitchen"), type = "joint")["yes"]

querygrain(setEvidence(gr_fit, nodes = "rent", states = "(687.072,1789.55]"),
           nodes = c("bathextra"), type = "joint")["yes"]
```